import type { Transaction } from '../db/schema';
import type { ReadPayload, Report } from '../types/ai';

export function formatAmount(amount: number): string {
  return `₩${amount.toLocaleString('ko-KR')}`;
}

export function formatType(type: 'income' | 'expense'): string {
  return type === 'income' ? '수입' : '지출';
}

export function generateCreateMessage(tx: Transaction): string {
  return `${formatType(tx.type)} ${formatAmount(tx.amount)} ${tx.memo || tx.category}로 ${tx.date}에 저장되었습니다`;
}

export function generateCreateMultipleMessage(transactions: Transaction[]): string {
  const totalAmount = transactions.reduce((sum, tx) => sum + tx.amount, 0);
  const summary = transactions
    .slice(0, 2)
    .map(tx => `${formatType(tx.type)} ${formatAmount(tx.amount)}`)
    .join(', ');
  const more = transactions.length > 2 ? ` 외 ${transactions.length - 2}개` : '';
  return `${summary}${more} 등 ${transactions.length}개 거래가 생성되었습니다 (총 ${formatAmount(totalAmount)})`;
}

export function generateUpdateMessage(tx: Transaction): string {
  return `거래가 수정되었습니다. ${formatType(tx.type)} ${formatAmount(tx.amount)} ${tx.memo || tx.category} (${tx.date})`;
}

export function generateUpdateMultipleMessage(transactions: Transaction[]): string {
  const totalAmount = transactions.reduce((sum, tx) => sum + tx.amount, 0);
  return `${transactions.length}개 거래가 수정되었습니다 (총액: ${formatAmount(totalAmount)})`;
}

export function generateDeleteMessage(tx: Transaction): string {
  return `${formatType(tx.type)} ${formatAmount(tx.amount)} ${tx.memo || tx.category} (${tx.date}) 삭제되었습니다. 최근 삭제된 항목에서 되돌릴 수 있습니다`;
}

export function generateDeleteMultipleMessage(transactions: Transaction[]): string {
  const totalAmount = transactions.reduce((sum, tx) => sum + tx.amount, 0);
  return `${transactions.length}개 거래가 삭제되었습니다 (총액: ${formatAmount(totalAmount)}). 최근 삭제된 항목에서 되돌릴 수 있습니다`;
}

export function generateUndoMessage(tx: Transaction): string {
  return `${formatType(tx.type)} ${formatAmount(tx.amount)} ${tx.memo || tx.category} (${tx.date}) 복원되었습니다`;
}

export function generateUndoDeleteMultipleMessage(transactions: Transaction[]): string {
  const totalAmount = transactions.reduce((sum, tx) => sum + tx.amount, 0);
  const summary = transactions
    .slice(0, 2)
    .map(tx => `${formatType(tx.type)} ${formatAmount(tx.amount)}`)
    .join(', ');
  const more = transactions.length > 2 ? ` 외 ${transactions.length - 2}개` : '';
  return `${summary}${more} 등 ${transactions.length}개 거래가 복원되었습니다 (총 ${formatAmount(totalAmount)})`;
}

export function generateUndoCreateMessage(count: number, totalAmount: number): string {
  return count === 1
    ? `방금 추가한 거래가 취소되었습니다`
    : `방금 추가한 ${count}개 거래가 취소되었습니다 (총 ${formatAmount(totalAmount)})`;
}

export function generateUndoUpdateMessage(transactions: Transaction[]): string {
  if (transactions.length === 1) {
    const tx = transactions[0];
    return `거래가 이전 상태로 복원되었습니다. ${formatType(tx.type)} ${formatAmount(tx.amount)} ${tx.memo || tx.category} (${tx.date})`;
  }
  const totalAmount = transactions.reduce((sum, tx) => sum + tx.amount, 0);
  return `${transactions.length}개 거래가 이전 상태로 복원되었습니다 (총액: ${formatAmount(totalAmount)})`;
}

export function generateReadMessage(
  transactions: Transaction[],
  totalAmount: number,
  filters: ReadPayload
): string {
  const count = transactions.length;
  const month = filters.month || new Date().toISOString().slice(0, 7);
  const category = filters.category ? ` ${filters.category}` : '';

  return `${month}월${category} 거래 ${count}건 조회됨 (총 ${formatAmount(totalAmount)})`;
}

export function generateErrorMessage(error: unknown): string {
  if (error instanceof Error) {
    return error.message;
  }
  return 'Unknown error occurred. Please try again.';
}

/**
 * Generates a formatted chat message response for a report
 * Converts Report object into message content with metadata
 * @param report - The Report object generated by AIReportService
 * @returns Object with content (for display) and metadata (for storing report data)
 */
export function generateReportMessage(report: Report): { content: string; metadata: Record<string, unknown> } {
  // Generate readable message content
  const content = `📊 ${report.title}${report.subtitle ? ' ' + report.subtitle : ''}

I've analyzed your financial data and generated the following insights:

${report.sections.map((section, i) => `${i + 1}. ${section.title}${section.subtitle ? ' - ' + section.subtitle : ''}`).join('\n')}

View the detailed analysis below.`;

  // Store full report data in metadata for rendering
  const metadata = {
    actionType: 'report',
    report: report,
  };

  return { content, metadata };
}
